### ISSUE TITLE
Christmas Party 2024

### ISSUE THREAD

**Issue by 0x4007** [0x4007/0x4007#5]
### Dates
- 22 December Sunday, mostly to cater to bartender friends
- (Possible) 25 December Wednesday, for the rest, depends on the feeling after the first event. 

### Live Music
- mentlegen has a connection for live bands get pricing 
- backup ask terry kim from get alright to book a group?
### Playlist
- Can make one on YouTube etc and use Josh's premium account for it. 

## Cocktail Program
- Get Pascal + Josh onboard
- Design Christmas cocktail menu
- Mulled wine(?)
- Top up ice and necessary spirits

## RSVPs
- Aiming for ~30 guests

### Photographer
- Find photographer

### Photo Zone
- All you @ana-0k just bear in mind that most of the colors are gold and white but red is also okay!

## Misc.
- Cleaning ladies should be booked on days after each. It might make sense to book 2x for 2.5 hours so they can handle cleaning faster/more efficiently.

**Comment by ana-0k** [comment]
### To-do list
---------

**Bar:**
- [x] Confirm bartenders via Pascal
- [x] Settle on 2-3 special xmas-themed cocktails
- [x] Ask Hobin best mulled wine & eggnog recipes
- [x] Top up spirits, ingredients & cocktail deco
- [x] Restock ice cubes
- [x] Find food options in advance (incl. charcuterie board)

**Other:**
- [x] Book photographer
- [x] Book a band
- [x] Set up photo wall+tripod with phone & light
- [x] Create playlist youtube
- [x] Book extra cleaning on Monday (assuming there is a regular one coming on Monday 2pm as well)

**Maybe:**
- [x] Get extra xmas props
- [ ] Get an xmas cake
- [ ] Make an invitation flyer
- [x] Get mini candy canes for cocktail & misc deco

----------------

Q1. December 22nd start time? (I suggest not later than 6pm considering ppl may be concerned cuz of work on Monday)
Q2. Desired time for the band?
Q3. Desired time for the photographer?
Q4. Regular cleaning lady will also come on Monday, right?

- Will share special cocktail suggestions with screenshots and recipes below, so we can settle on a few

**Comment by 0x4007** [comment]
> Q1. December 22nd start time? (I suggest not later than 6pm considering ppl may be concerned cuz of work on Monday)
> 

I don't think anybody would come before like 8p 

> Q2. Desired time for the band?
> 

10p and then another set after a break so maybe 11:30p.

> Q3. Desired time for the photographer?
> 

10p-1a I think is a good time

> Q4. Regular cleaning lady will also come on Monday, right?
> 

They should yes.

**Comment by 0x4007** [comment]
- We definitely need to top up on Mancino! I'm down to my last half bottle unfortunately. 3x bottles from Pascal
- Fernet Bianco 2x bottles. Lets order from namdaemun because Pascal says he hasn't been able to find it in most liquor stores.

**Comment by ana-0k** [comment]
Added up approximate amount $$ both for the xmas party and your side quests that need to be covered in December.
Only thing, idk how many bartenders there's gonna be and how much they are paid, so need to add that approx amount to the total

1. Alcohol+food - 1,000,000
2. Bartenders - 350,000
3. Music band - 1,000,000 ($700)
4. Photographer - 300,000
5. Cleaning (2hr x assuming 2 days) - 100,000
6. Misc - 500,000 (in case extra drinks/ingredients needed)
7. Styler DF24CB9900CR - 2,100,000
8. Apt rent for Jan - 3,600,000
9. Return to Jin for coupang - 700,000 (if haven’t yet)
—-
Total: 9,650,000 ~7k USD

**Comment by 0x4007** [comment]
> idk how many bartenders there's gonna be and how much they are paid

One or two and I think ~$25 USD per hour. Total of ~$250.

**Comment by ana-0k** [comment]
Updated list

1. Alcohol ~ 500,000
2. Food ~ 500,000
3. Pascal & Josh fee ~ 600,000 (?)
4. Bartenders - 300,000
5. Music band - 200,000
6. Photographer - 150,000
7. Cleaning x2 - 100,000
8. Ana already spent - 250,00 (props, food, etc)
9. Misc - 500,000 (in case extra drinks/ingredients needed)

Party: 3,400,000 ~2.5k USD


1. Styler DF24CB9900CR - 2,100,000
2. Apt rent for Jan - 3,600,000
3. Return to Jin for coupang - 700,000

Other: 6,400,000 ~4.5k USD

——-
Total Party+Other: 9,800,000 ~7k USD

**Comment by ana-0k** [comment]
Charcuterie board order (Fausto) / price TBC
Delivery: Sunday ~1pm

Cheese:
- Mozarella bocconcini (small in water) 1kg
- Burrata x3 packs (4ea in a pack)
- Brie 1 large wheel
- Provolone sliced ~400g
+Andrea will bring more hard cheese

Meat:
- 4 kinds x400g each
Mortadella - cubes
Prosciutto, salami, mild salami - thin slices

Olives:
- Pitted green ~ 500g
- Pitted black ~ 500g

---------

Coupang fresh order
Delivery: Sunday before 7am

- Mini fresh tomatoes 500g
- Basil leaves
- Cream cheese x2
- Crackers x4 packs
- Strawberry x1 pack
- Grapes white x1~2
- Pomegranate x1
- Sun-dried tomatoes

----

Coupang basic order
Delivery: Thu~Fri

- Pasta farfalle
- Crackers long
- Tartalette 60p
- Rosemary 100g
- Pesto

-----

Etc:
- I will bring nuts mix
- Will bring oranges and apples for mulled wine decoration
- Would be good to order 1~2 thin dough pizzas, coupang eats
- I'll come by 4~5pm on Sunday and set everything up

**Comment by ana-0k** [comment]
Fausto food quote
----

Ok, I've got the updated pricing:
Tell me if it's ok. I gave you a 25% discount, so the prices are already discounted:

Mozzarella bocconcini 1kg: 29k
Burrata x3 packs: 39k
Provolone sliced 400 gr: 26k
French Brie wheel 1kg: 55k
Olives black pitted 440 gr: 12k
Olives green pitted 440 gr: 12k
Prosciutto sliced 400 gr: 45k
Mortadella cubes 400 gr: 25k
Salami spicy sliced 400 gr: 36k
Salami mild sliced 400 gr: 36k
Fast Delivery Sunday early afternoon: 10k

Total: 325,000 krw including 10%vat

Let me know if it’s all good!

**Comment by 0x4007** [comment]
Sounds fine but expensive I hope it isn't too much and goes to waste. Hope we can slowly serve while keeping most in fridge during the night

**Comment by ana-0k** [comment]
So turns out $ was not usd but krw lol its total 325,000 won instead of 470k as i wrote before, fixed it in the comment above

**Comment by ana-0k** [comment]
Payments

- [x] Bartenders x2 - 25k/hr, 8hrs, 400,000won
- [x] Pascal & Josh, ingredients only - 534,660
- [x] Musicians x2 - 200,000won
- [ ] Photographer - 150,000won
